GET http://localhost:4000/

### new category

POST http://localhost:4000/api/shop/categories/new
Content-Type: application/json

{
    "title": "Bubble gum"
}

### get all categories

GET http://localhost:4000/api/shop/categories

### add new item
POST http://localhost:4000/api/shop/items/new
Content-Type: application/json

{
    "title": "green hat"
}

### Get all items
GET http://localhost:4000/api/shop/items


### Get single item
GET http://localhost:4000/api/shop/items/60e692334d9638b6a3e02e30

#### USERS
GET http://localhost:4000/api/shop/shopusers

### New User 
POST http://localhost:4000/api/shop/shopusers/new
Content-Type: application/json

{
    "name": "Mike Bloom",
    "email": "Mike@Bloom.com",
    "password": "secret1231"
}